Name: Production
Type: FolderType
Children:
- Name: PlannedProductionTime
  Type: BaseDataVariableType
  DataType: Double
- Name: ActualProductionTime
  Type: BaseDataVariableType
  DataType: Double
- Name: TotalDowntime
  Type: BaseDataVariableType
  DataType: Double
- Name: UnplannedDowntime
  Type: BaseDataVariableType
  DataType: Double
- Name: PlannedDowntime
  Type: BaseDataVariableType
  DataType: Double
