Name: Production
Type: FolderType
Children:
- Name: IdealCycleTimeSeconds
  Type: BaseDataVariableType
  DataType: Double
- Name: PlannedProductionTimeHours
  Type: BaseDataVariableType
  DataType: Double
- Name: NumberOfShifts
  Type: BaseDataVariableType
  DataType: Int32
- Name: ShiftStartTime
  Type: BaseDataVariableType
  DataType: String
- Name: ProductionTarget
  Type: BaseDataVariableType
  DataType: Int32
