Name: Production
Type: FolderType
Children:
- Name: IdealCycleTimeSeconds
  Type: BaseDataVariableType
  DataType: Double
- Name: PlannedProductionTimeHours
  Type: BaseDataVariableType
  DataType: Double
- Name: NumberOfShifts
  Type: BaseDataVariableType
  DataType: Int32
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "/Objects/Grosfillex_Line3_OEE/Model/ProductionSettings/ShiftSettings/NumberOfShifts"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      ModellingRule: Optional
      Value: 2
- Name: ShiftStartTime
  Type: BaseDataVariableType
  DataType: DateTime
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "/Objects/Grosfillex_Line3_OEE/Model/ProductionSettings/ShiftSettings/ShiftStartTime"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      ModellingRule: Optional
      Value: 2
- Name: ProductionTarget
  Type: BaseDataVariableType
  DataType: Int32
- Name: LineID
  Type: BaseDataVariableType
  DataType: String
  Value: "0"
